# GENERIC SETTINGS
DEBUG = False

# ASSEMBLY INFO
EXPECTED_TASKS = {"B": 0, "D": 1, "H": 2, "MT": 3, "S": 4, "W": 5}
ROBOT_TASK_TIME = {"B": [23.1], "D": [1000], "H": [22.3, 24.1], "MT": [1000], "S": [24.0], "W": [16.5, 1000]}

# ARDUINO CONNECTION
ARDUINO_BOARD = "Genuino Uno"

# CAMERA SETTINGS
STREAM_WIDTH = 1280
STREAM_HEIGHT = 720
STREAM_FPS = 30
SKIP_FRAMES = 2

# CLASSIFICATION SETTINGS
C_SEQ_LEN = 186
C_NUM_BLOCKS = 8
C_HIDDEN_DIM = 128
C_TEMPORAL_STRIDE = 2
C_RESIDUAL = True
C_ADAPTIVE = True
C_ATTENTION = True
C_FC_LAYERS = 1
C_FC_UNITS = 128
C_FC_DROPOUT = 0.2

# SEGMENTATION SETTINGS
S_SEQ_LEN = 11
S_NUM_BLOCKS = 8
S_HIDDEN_DIM = 128
S_TEMPORAL_STRIDE = 2
S_RESIDUAL = True
S_ADAPTIVE = True
S_ATTENTION = True
S_FC_LAYERS = 1
S_FC_UNITS = 128
S_FC_DROPOUT = 0.2
TIMING_WINDOW = 20
TIMING_THRESHOLD = 0.5